language: ruby
rvm:
- 2.7.2
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
before_script:
- psql -c 'create database db_test;' -U postgres
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: HbYnZoE2TmL2v9yFA8WQPZErEjijKwe4Heap4Yf/1LrxRy3sUN1S6H2l9iIQarK5qJNQ0WcECwDms3k8wcdJqjuc/cDLQVajlnnHG3OWgErCi9UcCZ1YH76hwXJanavcEIpUS0REhTJWHlm5s8Kd4Cz611aRn/iu+v+mNZRQVhpdIjoPASuXgyifgDHrJH5jm7LIN/LCp8k0lb01022/4P3+UA3oR5m8a4GmD2DRDuCIMw++Mr8R+Ed+/AkNZ/6kLUsjx2ExELCmZvS2Fpn0rZzqx2z/yZuVX8rtxW/A0mR5f5Idfq/ckXWuomMC/8swIsnlZtJegzvuKAUcZ1lZtKGlxI8SF9Ua1kJ27BO9QP2yM76359v0beE1SNf/8yujsxNlfPegwI4XrP/tvJT5OTPDmgMXdDSQGMqwgquqRbxKOtrGXCEIq/fP83qZU6l4B/2aY/pRp9Edad0vL5ulRdO320HmdNHlULq/gt1A1C8dCZfEzHVeburpYhUXeKrR0JZzEHQzZJvBTxRzp1/FYkYJiFrwI6VtSVNR5wjjgek2Fen779qyKLkPL1HNpEMI8IkuhWMRoAs5moBh0c9EQplewFk1lZYcVLnVDhkDT/nTY+OhX4229s6s/mdKLMowPCT33ro4mpW5hfW++w3hkYytX77546lRMZjcbhUWu2w=
  app: client-tell-presentation
  run: rails db:migrate
